### PR TITLE
Support custom parameters

### PR DESCRIPTION
**Pull request by KPR7168**
Since we don't have a way to pass [custom parameters](https://github.com/diegogarciar/twilio_voice/issues/14) yet, this PR addresses that. I'm also new to flutter, open to suggestions or better solutions.

Testing:
• Use [this](https://www.twilio.com/docs/voice/how-share-information-between-your-applications#using-the-call-resource) as a guide on how to pass custom params.
• I added a log in `onCallStateChanged` so that it'll print custom data if its not null

### CODE REVIEW

**Comment by diegog-sf** [comment]
Thank you @KPR7168, looks very good! I'll just do some small changes but thanks a lot for designing it!

**Comment by diegogarciar** [comment]
Thank you @KPR7168, looks very good! I'll just do some small changes but thanks a lot for designing it!

So one question, I see that you are sending this on 'Ringing' which I believe is only received on the caller and not the calle

**Comment by diegogarciar** [comment]
My mistake, it seems that ringing is sent on two places

**Comment by diegogarciar** [comment]
Hello @KPR7168, can you test these changes?

**Comment by KPR7168** [comment]
@diegogarciar looks good to me.

**Comment by diegog-sf** [comment]
Awesome, merging then!

**Pull request merged**
