### PR TITLE
Fix: CallDirection.outgoing even for Incoming Calls and Active Call is not null after the call is declined.

### LINKED ISSUE #130: CallDirection of Active Call is always CallDirection.outgoing.
On Callee Side.

Expected:
`Ringing - From: Alice, To: Bob, Direction: CallDirection.incoming`

Actual:
`Ringing - From: Alice, To: Bob, Direction: CallDirection.outgoing`

### LINKED ISSUE #132: ActiveCall is not null after call is declined.

### PR DESCRIPTION
**Pull request by agent515**
Fix: #130 #132 

- Remove hard coded `CallDirection.outgoing`.
- Make ActiveCall null once the call is declined.

### CODE REVIEW

**Comment by cybex-dev** [comment]
Many thanks for you PR, would you mind merging with latest changes and adding these to the semi-federated package: [method channel file](https://github.com/diegogarciar/twilio_voice/blob/master/lib/_internal/method_channel/twilio_voice_method_channel.dart).

I'll merge once done.

**Comment by cybex-dev** [comment]
Following up on proposed changes @agent515

**Comment by agent515** [comment]
Hi @cybex-dev . Sorry for the late revert. I've merged the latest changes from the master. Please have a look.

PS: There are some additional 'new_line' changes due to my linter like before. So please remove those if you want. 🙏

**Comment by cybex-dev** [comment]
> Hi @cybex-dev . Sorry for the late revert. I've merged the latest changes from the master. Please have a look.
> 
> PS: There are some additional 'new_line' changes due to my linter like before. So please remove those if you want. 🙏

Awesome, thank you very much!

Would it be possible do reduce some of those linter changes, alternatively reset git to a previous commit, add lines and force push update should also be fine.

**Comment by agent515** [comment]
@cybex-dev  Done. ✅

**Comment by cybex-dev** [comment]
@agent515 great stuff, thank you very much!

Would you mind documenting these changes in the [CHANGELOG](https://github.com/cybex-dev/twilio_voice/blob/master/CHANGELOG.md).

I'll review and test later today.

**Comment by agent515** [comment]
@cybex-dev should I write those in the CHANGELOG for the next release?

I'll add the following logs once confirmed.

- Fix: Showing `CallDirection.outgoing` instead of `CallDirection.incoming` when Incoming call is ringing in CallEventsListeners.
- Fix: Active Call is not null even after the Call is declined.

**Comment by cybex-dev** [comment]
Please do - let's everyone know who authored these changes.

**Comment by agent515** [comment]
@cybex-dev Done. ✅

**Review by cybex-dev — COMMENTED** [review]
Awesome!

**Pull request merged**
